export const CHANGE_BOOK_CHAPTERS = "CHANGE_BOOK_CHAPTERS";
export const CHANGE_BOOK_TITLE = "CHANGE_BOOK_TITLE";
export const CHANGE_BOOK_SOURCE = "CHANGE_BOOK_SOURCE";
export const CHANGE_BOOK_CONTENT = "CHANGE_BOOK_CONTENT";
export const CHANGE_BOOK_SOURCE_CURRENT = "CHANGE_BOOK_SOURCE_CURRENT";
export const STWICH_BOOK_SOURCE='STWICH_BOOK_SOURCE'
export const EMPTY_BOOK_CONTENT='EMPTY_BOOK_CONTENT'


